version: '3.4'
services:
  shortlinks:
    build:
      context: ../
      dockerfile: docker/Dockerfile
      target: php-local
    environment:
      DB_HOST: shortlinkdb
      DB_USER: root
      DB_PASSWORD: password
      DB_TABLE: shortlink
    volumes:
      - ../:/var/www/
    ports:
      - 80:80
  shortlinkdb:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - shortlinkdb-data:/var/lib/mysql
  composer-service:
    build:
      context: ../
      dockerfile: docker/Dockerfile
      target: local-composer
    volumes:
      - ../:/app/

volumes:
  shortlinkdb-data: